- name: feature
  description: New feature or request
  color: 2C4BE1
- name: bug
  description: Something isn't working
  color: D73A4A
- name: documentation
  description: Improvements or additions to documentation
  color: 0075CA
- name: contributions welcome
  description: Architecture is clear and community can help
  color: F488C1
- name: dev-infra
  description: dev infra
  color: 3F2963
- name: ready to merge
  description: ready
  color: 0E8A16
- name: "state: need triage"
  description: state need triage
  color: C5DEF5