name: 🤖 Auto sync labels
on:
  push:
    branches: [main]
    paths:
      - .github/labels.yml
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.ROUTELINKBOT_TOKEN }}
      - name: Sync labels
        uses: micnncim/action-label-syncer@v1.3.0
        with:
          manifest: .github/labels.yml
          token: ${{ secrets.ROUTELINKBOT_TOKEN }}
          prune: true
          repository: |
            routelink/.github
            routelink/client
            routelink/server
